### ISSUE TITLE
FEATURE - Going back after viewing a contact details, should return to the search results without resetting it

### ISSUE THREAD

**Issue by GuilhermeTorq** [Goodwy/Contacts#11]
When making a search for a contact and pressing it to see more details and then going back, the search results get's resettled. And it's just annoying because I have to make the search again every time.

Can this feature be implemented? To keep the search results instead of resetting?

**Comment by Goodwy** [comment]
That's not happening to me. Can you send me a screen capture?

**Comment by GuilhermeTorq** [comment]
https://github.com/user-attachments/assets/5c08d711-f75b-4d77-975d-9b7c4714a543

Tried to make it as visible as possible, blurred out the contacts. But as you can hopefully see by the contact coloured icons, the search resets to the default when going back from the contact details.

(if possible I would appreciate to know when I can remove the video, as I don't really want it on the ethernet, thanks)

**Comment by Goodwy** [comment]
Thank you. Fixed it, will come out in the next version.
