### ISSUE TITLE
Setting to move contacts starting with "*" and "@" down 

### ISSUE THREAD

**Issue by Moostek** [Goodwy/Contacts#3]
Hello, it will perfect to have contacs starting with "*" and "@" down, under the "Z". Can you make setting for this, please?

**Comment by Goodwy** [comment]
Will be implemented in the next version as a setting in the sorting dialog.

**Comment by Moostek** [comment]
Hello, was this feature already implemented? I can not find any settings of this kind.

**Comment by Goodwy** [comment]
Implemented, the sort dialog box has this setting.

**Comment by Moostek** [comment]
Can you tell me what is the name for this setting to put contacts starting with "@" and "*" down? I have not find it. I use CZ localization.

**Comment by Goodwy** [comment]
"Symboly jako první (např. !@#$)"
It's not in the settings, it's in the sort dialog.

**Comment by Moostek** [comment]
Ok, I got it. Thanks.
