### ISSUE TITLE
Another paying method(s) to get Goodwy PRO features (PayPal) 

### ISSUE THREAD

**Issue by Moostek** [Goodwy/Contacts#5]
Hello, I have one general question about your apps (namely Dialer, Contacts and Messages). I do not use Google account and also any Google framework on my phone, I use only free open-source app, incl. Aurora App Store. The problem is that I can not unlock PRO features on your apps, because I do not use GooglePlay (Google account). 

I would like to support your effort and apps with buying the extra features, but it is not possible! Can you get rid off of GooglePlay monopoly and give users another options to get the PRO features, please? For example via PayPal, this is good option. 

For example, the FairEmail open-source email client app has perfectly managed PRO feature purchasing system via PayPal. The combination of PayPal and email is so easy and fast. Find the inspiration from the FairMail, please. 

Thank you!

**Comment by Goodwy** [comment]
This has been fixed in recent versions. If you don't have Google Play on your device, you can unlock all app features manually

**Comment by Moostek** [comment]
Ok, excellent. Thank you.
