### ISSUE TITLE
BUG: Contacts do not interlink 

### ISSUE THREAD

**Issue by Moostek** [Goodwy/Contacts#6]
Hello, I found that **Right Contacts app does not interlink the contacts with my dialer (Right Dialer app), i.e. with Google Contacts app**. When I create a new contact or when I record back up contacts file via Right Contacts app, the contacts are "blind". 

The situation 1:
In last calls list of the Right Dialer app I can not see the name of the contact after I saved this number via Right Contacts app, I still can see there just the number. 

The situation 2: 
When I clone or record the saved backed up contacts from a file via Right Contacts, these contacts are "blind", they are not connected with the last calls list of the Right Dialer app, I can see just numbers, not names. It also takes no effect to my SMS app, the contacts are without names, just numbers. 

I made some exploration about this, and I found that when I save the number via Google Contacts app, the Right Dialer app connect this number and view its name in dialer's last call list (Right Dialer app). Also, when i record back up contacts file via Google Contacts app, the contacts are visible in Right Dialer app (las calls list) and also all SMS they are connected with names. 

I tested this with other open-source Contact app, and it worked: the app reflected changes in Google Contacts and vice versa. 

**So it seems that Right Contacts does not communicate with Google Contacts.** 

Thank you for fixing this! 

p.s.: On another LineageOS with newer update of v16.0 from 2020 it worked I think, but I do not have this phone, I use a bit older release (can not update now).

**Comment by Goodwy** [comment]
It looks like you used private contacts, which create a record only inside our app, other apps will not have access to them. Check the source of the contact when adding a new contact.

**Comment by Moostek** [comment]
How do I create "private contacts" with Right Contacts? I have no knowledge that I even tried to create contacts as private ones, I do not even know how to do it. I just used the Right Contact app to save the number, did nothing more. 

So I really belive that there is a bug in Right Contacts app with the procedure of saving the new numbers and restoring the backed up contact list. Because it is really strange that with other contacts apps it worked, but with Right Contacts it did not. 

PS: the cause might be also the phone number format. My phone has from some reason the XXX-XXX-XXXXXXXX number format. I found that to interlink the numbers with the Dialer and SMS app helps to manually change the format of the number in the Google Contacts app.

**Comment by Goodwy** [comment]
When creating a new contact or viewing a contact, there is a Contact Source field at the very bottom. If you select the source "Phone storage (not visible to other applications)", the contact will not be visible in third-party applications. It is possible to give other applications (Dialen, SMS manager) access to these contacts through settings.

**Comment by Moostek** [comment]
How do I create "private contacts" with Right Contacts? I have no knowledge that I even tried to create contacts as private ones, I do not even know how to do it. I just used the Right Contact app to save the number, did nothing more. 

So I really belive that there is a bug in Right Contacts app with the procedure of saving the new numbers and restoring the backed up contact list. Because it is really strange that with other contacts apps it worked, but with Right Contacts it did not. 

PS: the cause might be also the phone number format. My phone has from some reason the XXX-XXX-XXXXXXXX number format. I found that to interlink the numbers with the Dialer and SMS app helps to manually change the format of the number in the Google Contacts app.

**Comment by Moostek** [comment]
Well, I am 100% sure that I did not save the numbers as private ones. So it seems that there must be some bug. With other apps it worked out (as I stated above).

**Comment by Goodwy** [comment]
You can't create such a private contact in other apps. You can verify this by looking at the contact source for the problem contact.

**Comment by Moostek** [comment]
As I wrote, I did not create new contacts as private ones in Right Contacts app. So there must be something wrong with this in Right apps. With other 3rd party apps the numbers interlinked.

**Comment by Goodwy** [comment]
If some contacts are not visible in our application, it means that either a filter is set or contact merging is enabled.
