### ISSUE TITLE
Favorites

### ISSUE THREAD

**Issue by theLittlePrinceAD** [Goodwy/Contacts#9]
When adding Favorites by pressing the Star in a chosen Contact (from one of the sources - outlook.com f.e.) - Contacts from all sources (outlook.com, skype, whatsapp, etc.) are being added to Favorites, not just the active source (outlook.com). In other words I get 4-5-6 Favorites instead of only one.

**Comment by Goodwy** [comment]
У вас контакты не сгруппированы?

**Comment by Goodwy** [comment]
Do you have your contacts ungrouped?

**Comment by theLittlePrinceAD** [comment]
Hello, sorry for answering late.
I wish you personal happiness and professional success throughout the new 2024 year!

Regarding the question: I have re-installed in the past days my Exchange account. Apparently - I had an database error on my side before, as now the error I have mentioned in this post does not show up again. It seems the Right Contacts app is working as expected.
BR
